### ISSUE TITLE
Bug with nodemon

### ISSUE THREAD

**Issue by marioteik** [EricKit/nest-user-auth#1]
This project is restarting all the time when you use nodemon because of the graphql.clases.ts. You need to ignore it on nodemon.json or find another better solution.

**Comment by EricKit** [comment]
Thanks for the feedback. I added comments to front page on how to fix this (I've never used nodemon, I like it!). It's above the GraphQL section. Let me know if this doesn't close your issue.

**Comment by marioteik** [comment]
Hi, I did not see this comment early, sry.

Nodemon is pretty common. Nestjs put it on the projetc, so I think the solution should be to ignore the changes on graphql.classes.ts. Is very hand the definition generated on this file and the tslint can handle update on the fly, so ignoring changes on it doesn't affect the project at all and will help development a lot.

My workaround was like this:

To use nodemon you'll need to make a small change. In 'nodemon.json' you should add "src/graphql.classes.ts" to ignore the changes on that file.

```json
{
  "watch": ["src"],
  "ext": "ts,graphql",
  "ignore": ["src/**/*.spec.ts", "src/**/graphql.classes.ts"],
  "exec": "ts-node -r tsconfig-paths/register src/main.ts"
}
```
Anyway, good job on this project!

**Comment by EricKit** [comment]
Perfect, made the change. Thanks!
