### ISSUE TITLE
Expiration Bug

### ISSUE THREAD

**Issue by spali** [EricKit/nest-user-auth#2]
Hi
Thanks for this good example, helped a lot.
I think I found a bug with the expiration date at
https://github.com/EricKit/nest-user-auth/blob/cf33a7743af18ecf8def2d4810b3d915e25d2650/src/auth/auth.service.ts#L108

`setSeconds` does only set the second portion of a `Date` object. This would result in an unexpected date.
See explanation about the same with `setMilliseconds` here: https://stackoverflow.com/a/12795802
Also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setSeconds

I think the simplest would be to use `getTime()` and `setTime()`:
```js
expiration.setTime(expiration.getTime() + expiresIn * 1000); 
```
or
```js
expiration = new Date(expiration.getTime() + expiresIn * 1000)); 
```

**Comment by EricKit** [comment]
Great catch, thanks!
